### ISSUE TITLE
AttributeError: module '__main__' has no attribute '__spec__'

### ISSUE THREAD

**Issue by yzhenggit** [rcooke-ast/ALIS#17] opened 2021-06-03 22:38 UTC
Hi, 

My student and I are trying to use ALIS to reduce some absorption line data. We run into a problem as the following: 

AttributeError: module '__main__' has no attribute '__spec__'

The full traceback error can be found here: 
[alis_error.txt](https://github.com/rcooke-ast/ALIS/files/6594698/alis_error.txt)

Seems like it's related to multiprocessing, although we have no clues as to how to fix it. Could you give us some advice on this? Thank you!

**Comment by rcooke-ast** [comment] 2021-06-10 08:00
Hi Yong,

Thanks for the full traceback... That's a strange one, and I've not encountered it before. Also, I'm unable to reproduce the issue, so it makes this particular bug a little difficult to diagnose. However, I suspect it's something with either the multiprocessing module or, perhaps more likely, something about the way ALIS is being invoked. Are you using conda, spyder, an IPython notebook, or something else?

It might be possible to just add the line `__spec__ = None` at the top of `alcsmin.py` (immediately after the imports, on line 42). If that doesn't work, you might be able to put `self.__spec__ = None` inside the init method of the `alcsmin.alfit` class (i.e. in the same file, around line 326).

Failing that, it might be helpful to compare the versions of the packages you are using, to the ones that I'm using (i.e. versions of python and multiprocessing).

I hope that helps! If one of the above hacks works OK, please let me know, so we can include the fix in ALIS just in case others encounter the same problem. Thanks!!

**Comment by yzhenggit** [comment] 2021-06-15 01:18
Hi Ryan, thanks for your reply! We tried to add the line to the corresponding file as you suggested, it wasn't successful. The code crashed with the same error... 

I'm using python 3.6.8, with which I can run ALIS without any problem. My student's mac has python 3.8, although it doesn't seem to work when we tried to reverse it back to an older version. 

Could it be related to the Mac OS system? I think my student has the Big Sur.

**Comment by rcooke-ast** [comment] 2021-06-15 10:15
Hmmm... I've just tested this on Big Sur, python 3.8.5 and I'm not encountering any problem. That said, I used conda to setup my python. On the computer you are encountering a problem, has python been setup using conda, spyder, or something else (perhaps the default setup that comes with a Mac OS)? The easiest thing to check is to open a terminal, change into the `ALIS/examples/metal_line_abs/model` folder, and then run the following two commands:
```
run_alis generate_spectra.mod
run_alis fit_spectra.mod
```
Also, I realised a typo in my earlier message (now fixed)... You could try putting the following on line 326: `self.__spec__ = None`

Let me know what you find out from the above, and we can take it from there!

**Comment by yzhenggit** [comment] 2021-07-09 22:42
Hi Ryan, sorry for replying to this so late! My undergrad tried what you suggested, but still wasn't able to get it to work. It was the same error. I think it's probably a problem unique to his laptop, hence not universal. We eventually decided to have him working on something else instead of Voigt profile fitting. But thank you all the same! I really appreciate your time and advice on fixing this issue!

**Comment by rcooke-ast** [comment] 2021-07-10 06:20
Thanks for letting me know - I'll close this issue for now. It has appeared multiprocessing before, so I think it's unlikely related to ALIS... at least that's what I suspect.

**Closed as completed by rcooke-ast** 2021-07-10 06:20 UTC
